<?php

/**
 * A curated country directory — ISO 3166-1 alpha-2 code, name, phone dial
 * code, ISO 4217 currency, and IANA timezone(s) — used to power the
 * country/timezone/currency/phone-code dropdowns on Registration and
 * Settings, and their browser-side auto-detection (resources/js/geo.js).
 *
 * Single source of truth: this file feeds both the PHP-side <select>
 * options and (via @json in the geo-detect script) the JS-side timezone
 * lookup table, so the two are never out of sync with each other.
 *
 * 'tz' is the country's most representative zone (used to prefill
 * Settings/Registration once a country is chosen or detected). Countries
 * that genuinely span multiple zones also list 'tzs' — every zone in
 * that list resolves back to the country for detection purposes.
 */
return [
    ['code' => 'NG', 'name' => 'Nigeria', 'dial' => '+234', 'currency' => 'NGN', 'tz' => 'Africa/Lagos'],
    ['code' => 'GH', 'name' => 'Ghana', 'dial' => '+233', 'currency' => 'GHS', 'tz' => 'Africa/Accra'],
    ['code' => 'KE', 'name' => 'Kenya', 'dial' => '+254', 'currency' => 'KES', 'tz' => 'Africa/Nairobi'],
    ['code' => 'ZA', 'name' => 'South Africa', 'dial' => '+27', 'currency' => 'ZAR', 'tz' => 'Africa/Johannesburg'],
    ['code' => 'EG', 'name' => 'Egypt', 'dial' => '+20', 'currency' => 'EGP', 'tz' => 'Africa/Cairo'],
    ['code' => 'MA', 'name' => 'Morocco', 'dial' => '+212', 'currency' => 'MAD', 'tz' => 'Africa/Casablanca'],
    ['code' => 'DZ', 'name' => 'Algeria', 'dial' => '+213', 'currency' => 'DZD', 'tz' => 'Africa/Algiers'],
    ['code' => 'TN', 'name' => 'Tunisia', 'dial' => '+216', 'currency' => 'TND', 'tz' => 'Africa/Tunis'],
    ['code' => 'ET', 'name' => 'Ethiopia', 'dial' => '+251', 'currency' => 'ETB', 'tz' => 'Africa/Addis_Ababa'],
    ['code' => 'TZ', 'name' => 'Tanzania', 'dial' => '+255', 'currency' => 'TZS', 'tz' => 'Africa/Dar_es_Salaam'],
    ['code' => 'UG', 'name' => 'Uganda', 'dial' => '+256', 'currency' => 'UGX', 'tz' => 'Africa/Kampala'],
    ['code' => 'RW', 'name' => 'Rwanda', 'dial' => '+250', 'currency' => 'RWF', 'tz' => 'Africa/Kigali'],
    ['code' => 'SN', 'name' => 'Senegal', 'dial' => '+221', 'currency' => 'XOF', 'tz' => 'Africa/Dakar'],
    ['code' => 'CI', 'name' => "Cote d'Ivoire", 'dial' => '+225', 'currency' => 'XOF', 'tz' => 'Africa/Abidjan'],
    ['code' => 'CM', 'name' => 'Cameroon', 'dial' => '+237', 'currency' => 'XAF', 'tz' => 'Africa/Douala'],
    ['code' => 'ZM', 'name' => 'Zambia', 'dial' => '+260', 'currency' => 'ZMW', 'tz' => 'Africa/Lusaka'],
    ['code' => 'ZW', 'name' => 'Zimbabwe', 'dial' => '+263', 'currency' => 'ZWL', 'tz' => 'Africa/Harare'],
    ['code' => 'MZ', 'name' => 'Mozambique', 'dial' => '+258', 'currency' => 'MZN', 'tz' => 'Africa/Maputo'],
    ['code' => 'AO', 'name' => 'Angola', 'dial' => '+244', 'currency' => 'AOA', 'tz' => 'Africa/Luanda'],
    ['code' => 'BW', 'name' => 'Botswana', 'dial' => '+267', 'currency' => 'BWP', 'tz' => 'Africa/Gaborone'],
    ['code' => 'NA', 'name' => 'Namibia', 'dial' => '+264', 'currency' => 'NAD', 'tz' => 'Africa/Windhoek'],
    ['code' => 'ML', 'name' => 'Mali', 'dial' => '+223', 'currency' => 'XOF', 'tz' => 'Africa/Bamako'],
    ['code' => 'BF', 'name' => 'Burkina Faso', 'dial' => '+226', 'currency' => 'XOF', 'tz' => 'Africa/Ouagadougou'],
    ['code' => 'BJ', 'name' => 'Benin', 'dial' => '+229', 'currency' => 'XOF', 'tz' => 'Africa/Porto-Novo'],
    ['code' => 'TG', 'name' => 'Togo', 'dial' => '+228', 'currency' => 'XOF', 'tz' => 'Africa/Lome'],
    ['code' => 'SL', 'name' => 'Sierra Leone', 'dial' => '+232', 'currency' => 'SLE', 'tz' => 'Africa/Freetown'],
    ['code' => 'LR', 'name' => 'Liberia', 'dial' => '+231', 'currency' => 'LRD', 'tz' => 'Africa/Monrovia'],
    ['code' => 'GM', 'name' => 'Gambia', 'dial' => '+220', 'currency' => 'GMD', 'tz' => 'Africa/Banjul'],
    ['code' => 'GN', 'name' => 'Guinea', 'dial' => '+224', 'currency' => 'GNF', 'tz' => 'Africa/Conakry'],
    ['code' => 'CD', 'name' => 'DR Congo', 'dial' => '+243', 'currency' => 'CDF', 'tz' => 'Africa/Kinshasa'],
    ['code' => 'CG', 'name' => 'Congo', 'dial' => '+242', 'currency' => 'XAF', 'tz' => 'Africa/Brazzaville'],
    ['code' => 'SD', 'name' => 'Sudan', 'dial' => '+249', 'currency' => 'SDG', 'tz' => 'Africa/Khartoum'],
    ['code' => 'SS', 'name' => 'South Sudan', 'dial' => '+211', 'currency' => 'SSP', 'tz' => 'Africa/Juba'],
    ['code' => 'SO', 'name' => 'Somalia', 'dial' => '+252', 'currency' => 'SOS', 'tz' => 'Africa/Mogadishu'],
    ['code' => 'LY', 'name' => 'Libya', 'dial' => '+218', 'currency' => 'LYD', 'tz' => 'Africa/Tripoli'],
    ['code' => 'MW', 'name' => 'Malawi', 'dial' => '+265', 'currency' => 'MWK', 'tz' => 'Africa/Blantyre'],
    ['code' => 'MU', 'name' => 'Mauritius', 'dial' => '+230', 'currency' => 'MUR', 'tz' => 'Indian/Mauritius'],

    ['code' => 'GB', 'name' => 'United Kingdom', 'dial' => '+44', 'currency' => 'GBP', 'tz' => 'Europe/London'],
    ['code' => 'IE', 'name' => 'Ireland', 'dial' => '+353', 'currency' => 'EUR', 'tz' => 'Europe/Dublin'],
    ['code' => 'FR', 'name' => 'France', 'dial' => '+33', 'currency' => 'EUR', 'tz' => 'Europe/Paris'],
    ['code' => 'DE', 'name' => 'Germany', 'dial' => '+49', 'currency' => 'EUR', 'tz' => 'Europe/Berlin'],
    ['code' => 'ES', 'name' => 'Spain', 'dial' => '+34', 'currency' => 'EUR', 'tz' => 'Europe/Madrid'],
    ['code' => 'PT', 'name' => 'Portugal', 'dial' => '+351', 'currency' => 'EUR', 'tz' => 'Europe/Lisbon'],
    ['code' => 'IT', 'name' => 'Italy', 'dial' => '+39', 'currency' => 'EUR', 'tz' => 'Europe/Rome'],
    ['code' => 'NL', 'name' => 'Netherlands', 'dial' => '+31', 'currency' => 'EUR', 'tz' => 'Europe/Amsterdam'],
    ['code' => 'BE', 'name' => 'Belgium', 'dial' => '+32', 'currency' => 'EUR', 'tz' => 'Europe/Brussels'],
    ['code' => 'CH', 'name' => 'Switzerland', 'dial' => '+41', 'currency' => 'CHF', 'tz' => 'Europe/Zurich'],
    ['code' => 'AT', 'name' => 'Austria', 'dial' => '+43', 'currency' => 'EUR', 'tz' => 'Europe/Vienna'],
    ['code' => 'SE', 'name' => 'Sweden', 'dial' => '+46', 'currency' => 'SEK', 'tz' => 'Europe/Stockholm'],
    ['code' => 'NO', 'name' => 'Norway', 'dial' => '+47', 'currency' => 'NOK', 'tz' => 'Europe/Oslo'],
    ['code' => 'DK', 'name' => 'Denmark', 'dial' => '+45', 'currency' => 'DKK', 'tz' => 'Europe/Copenhagen'],
    ['code' => 'FI', 'name' => 'Finland', 'dial' => '+358', 'currency' => 'EUR', 'tz' => 'Europe/Helsinki'],
    ['code' => 'PL', 'name' => 'Poland', 'dial' => '+48', 'currency' => 'PLN', 'tz' => 'Europe/Warsaw'],
    ['code' => 'CZ', 'name' => 'Czechia', 'dial' => '+420', 'currency' => 'CZK', 'tz' => 'Europe/Prague'],
    ['code' => 'GR', 'name' => 'Greece', 'dial' => '+30', 'currency' => 'EUR', 'tz' => 'Europe/Athens'],
    ['code' => 'RO', 'name' => 'Romania', 'dial' => '+40', 'currency' => 'RON', 'tz' => 'Europe/Bucharest'],
    ['code' => 'HU', 'name' => 'Hungary', 'dial' => '+36', 'currency' => 'HUF', 'tz' => 'Europe/Budapest'],
    ['code' => 'UA', 'name' => 'Ukraine', 'dial' => '+380', 'currency' => 'UAH', 'tz' => 'Europe/Kyiv'],
    ['code' => 'RU', 'name' => 'Russia', 'dial' => '+7', 'currency' => 'RUB', 'tz' => 'Europe/Moscow', 'tzs' => ['Europe/Moscow', 'Europe/Kaliningrad', 'Asia/Yekaterinburg', 'Asia/Omsk', 'Asia/Krasnoyarsk', 'Asia/Irkutsk', 'Asia/Yakutsk', 'Asia/Vladivostok', 'Asia/Kamchatka']],
    ['code' => 'TR', 'name' => 'Turkey', 'dial' => '+90', 'currency' => 'TRY', 'tz' => 'Europe/Istanbul'],

    ['code' => 'US', 'name' => 'United States', 'dial' => '+1', 'currency' => 'USD', 'tz' => 'America/New_York', 'tzs' => ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Phoenix', 'America/Los_Angeles', 'America/Anchorage', 'Pacific/Honolulu']],
    ['code' => 'CA', 'name' => 'Canada', 'dial' => '+1', 'currency' => 'CAD', 'tz' => 'America/Toronto', 'tzs' => ['America/St_Johns', 'America/Halifax', 'America/Toronto', 'America/Winnipeg', 'America/Regina', 'America/Edmonton', 'America/Vancouver']],
    ['code' => 'MX', 'name' => 'Mexico', 'dial' => '+52', 'currency' => 'MXN', 'tz' => 'America/Mexico_City', 'tzs' => ['America/Mexico_City', 'America/Tijuana', 'America/Cancun', 'America/Chihuahua']],
    ['code' => 'BR', 'name' => 'Brazil', 'dial' => '+55', 'currency' => 'BRL', 'tz' => 'America/Sao_Paulo', 'tzs' => ['America/Sao_Paulo', 'America/Manaus', 'America/Rio_Branco', 'America/Noronha']],
    ['code' => 'AR', 'name' => 'Argentina', 'dial' => '+54', 'currency' => 'ARS', 'tz' => 'America/Argentina/Buenos_Aires'],
    ['code' => 'CL', 'name' => 'Chile', 'dial' => '+56', 'currency' => 'CLP', 'tz' => 'America/Santiago'],
    ['code' => 'CO', 'name' => 'Colombia', 'dial' => '+57', 'currency' => 'COP', 'tz' => 'America/Bogota'],
    ['code' => 'PE', 'name' => 'Peru', 'dial' => '+51', 'currency' => 'PEN', 'tz' => 'America/Lima'],
    ['code' => 'VE', 'name' => 'Venezuela', 'dial' => '+58', 'currency' => 'VES', 'tz' => 'America/Caracas'],
    ['code' => 'EC', 'name' => 'Ecuador', 'dial' => '+593', 'currency' => 'USD', 'tz' => 'America/Guayaquil'],
    ['code' => 'JM', 'name' => 'Jamaica', 'dial' => '+1876', 'currency' => 'JMD', 'tz' => 'America/Jamaica'],
    ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'dial' => '+1868', 'currency' => 'TTD', 'tz' => 'America/Port_of_Spain'],

    ['code' => 'CN', 'name' => 'China', 'dial' => '+86', 'currency' => 'CNY', 'tz' => 'Asia/Shanghai'],
    ['code' => 'IN', 'name' => 'India', 'dial' => '+91', 'currency' => 'INR', 'tz' => 'Asia/Kolkata'],
    ['code' => 'PK', 'name' => 'Pakistan', 'dial' => '+92', 'currency' => 'PKR', 'tz' => 'Asia/Karachi'],
    ['code' => 'BD', 'name' => 'Bangladesh', 'dial' => '+880', 'currency' => 'BDT', 'tz' => 'Asia/Dhaka'],
    ['code' => 'JP', 'name' => 'Japan', 'dial' => '+81', 'currency' => 'JPY', 'tz' => 'Asia/Tokyo'],
    ['code' => 'KR', 'name' => 'South Korea', 'dial' => '+82', 'currency' => 'KRW', 'tz' => 'Asia/Seoul'],
    ['code' => 'ID', 'name' => 'Indonesia', 'dial' => '+62', 'currency' => 'IDR', 'tz' => 'Asia/Jakarta', 'tzs' => ['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']],
    ['code' => 'MY', 'name' => 'Malaysia', 'dial' => '+60', 'currency' => 'MYR', 'tz' => 'Asia/Kuala_Lumpur'],
    ['code' => 'SG', 'name' => 'Singapore', 'dial' => '+65', 'currency' => 'SGD', 'tz' => 'Asia/Singapore'],
    ['code' => 'PH', 'name' => 'Philippines', 'dial' => '+63', 'currency' => 'PHP', 'tz' => 'Asia/Manila'],
    ['code' => 'VN', 'name' => 'Vietnam', 'dial' => '+84', 'currency' => 'VND', 'tz' => 'Asia/Ho_Chi_Minh'],
    ['code' => 'TH', 'name' => 'Thailand', 'dial' => '+66', 'currency' => 'THB', 'tz' => 'Asia/Bangkok'],
    ['code' => 'AE', 'name' => 'United Arab Emirates', 'dial' => '+971', 'currency' => 'AED', 'tz' => 'Asia/Dubai'],
    ['code' => 'SA', 'name' => 'Saudi Arabia', 'dial' => '+966', 'currency' => 'SAR', 'tz' => 'Asia/Riyadh'],
    ['code' => 'QA', 'name' => 'Qatar', 'dial' => '+974', 'currency' => 'QAR', 'tz' => 'Asia/Qatar'],
    ['code' => 'KW', 'name' => 'Kuwait', 'dial' => '+965', 'currency' => 'KWD', 'tz' => 'Asia/Kuwait'],
    ['code' => 'IL', 'name' => 'Israel', 'dial' => '+972', 'currency' => 'ILS', 'tz' => 'Asia/Jerusalem'],
    ['code' => 'JO', 'name' => 'Jordan', 'dial' => '+962', 'currency' => 'JOD', 'tz' => 'Asia/Amman'],
    ['code' => 'LB', 'name' => 'Lebanon', 'dial' => '+961', 'currency' => 'LBP', 'tz' => 'Asia/Beirut'],
    ['code' => 'IQ', 'name' => 'Iraq', 'dial' => '+964', 'currency' => 'IQD', 'tz' => 'Asia/Baghdad'],
    ['code' => 'IR', 'name' => 'Iran', 'dial' => '+98', 'currency' => 'IRR', 'tz' => 'Asia/Tehran'],
    ['code' => 'LK', 'name' => 'Sri Lanka', 'dial' => '+94', 'currency' => 'LKR', 'tz' => 'Asia/Colombo'],
    ['code' => 'NP', 'name' => 'Nepal', 'dial' => '+977', 'currency' => 'NPR', 'tz' => 'Asia/Kathmandu'],
    ['code' => 'KZ', 'name' => 'Kazakhstan', 'dial' => '+7', 'currency' => 'KZT', 'tz' => 'Asia/Almaty', 'tzs' => ['Asia/Almaty', 'Asia/Aqtobe']],
    ['code' => 'HK', 'name' => 'Hong Kong', 'dial' => '+852', 'currency' => 'HKD', 'tz' => 'Asia/Hong_Kong'],
    ['code' => 'TW', 'name' => 'Taiwan', 'dial' => '+886', 'currency' => 'TWD', 'tz' => 'Asia/Taipei'],

    ['code' => 'AU', 'name' => 'Australia', 'dial' => '+61', 'currency' => 'AUD', 'tz' => 'Australia/Sydney', 'tzs' => ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane', 'Australia/Adelaide', 'Australia/Perth', 'Australia/Darwin', 'Australia/Hobart']],
    ['code' => 'NZ', 'name' => 'New Zealand', 'dial' => '+64', 'currency' => 'NZD', 'tz' => 'Pacific/Auckland'],
    ['code' => 'FJ', 'name' => 'Fiji', 'dial' => '+679', 'currency' => 'FJD', 'tz' => 'Pacific/Fiji'],
];
